### ISSUE TITLE
JOSS review: features

### ISSUE THREAD

**Issue by tkoskela** [henry2004y/Vlasiator.jl#122]
- [x] The usage examples seem to assume you have access to data from Vlasiator. It's difficult to comment on the features because the examples won't run without data. I noticed the benchmarks pull data from an artifact, could you provide data for the examples as well?

ref https://github.com/openjournals/joss-reviews/issues/4906

**Comment by henry2004y** [comment]
The way to obtain test data is described [here](https://henry2004y.github.io/Vlasiator.jl/stable/log/#Test-Data). We noticed that the other reviewer also had comments on this, which indicates that this part should be moved to another proper section in the documentation. WIP.

**Comment by tkoskela** [comment]
Again, sorry, the Log section confused me. Could you put a link to it in the "Loading VLSV data" section?

**Comment by henry2004y** [comment]
Added via fc939de2b1016175. It should show up in the updated dev document, and in the stable document on v0.9.34 is released after addressing all the issues.

**Comment by tkoskela** [comment]
Sorry for taking so long to review. I can run the examples and the Pluto notebook looks very cool! I'm happy to close this, I'd like to note that the `Plotting` section of the notebook does not work for me with the `bulk.amr.vlsv` file, maybe that is to be expected since you talk about cell IDs without AMR in the markdown.

This is the error I get

```
UndefVarError: origin not defined

macro expansion@plots.jl:49[inlined]
apply_recipe(::AbstractDict{Symbol, Any}, ::Vlasiator.MetaVLSV, ::AbstractString)@RecipesBase.jl:289
_process_userrecipes!(::Any, ::Any, ::Any)@user_recipe.jl:36
recipe_pipeline!(::Any, ::Any, ::Any)@RecipesPipeline.jl:70
_plot!(::Plots.Plot, ::Any, ::Any)@plot.jl:208
#plot#139@plot.jl:91[inlined]
var"#contourf#457"(::Base.Pairs{Symbol, V, Tuple{Vararg{Symbol, N}}, NamedTuple{names, T}} where {V, N, names, T<:Tuple{Vararg{Any, N}}}, ::typeof(Plots.contourf), ::Any, ::Vararg{Any})@RecipesBase.jl:410
top-level scope@Local: 3[inlined]
```
